package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"sort"
	"strings"
)

type terraformState struct {
	Resources []stateResource `json:"resources"`
}

type stateResource struct {
	Address   string          `json:"address"`
	Mode      string          `json:"mode"`
	Type      string          `json:"type"`
	Name      string          `json:"name"`
	Module    string          `json:"module"`
	Instances []stateInstance `json:"instances"`
}

type stateInstance struct {
	IndexKey   interface{}            `json:"index_key"`
	Attributes map[string]interface{} `json:"attributes"`
}

type groupItem struct {
	ID           string
	Name         string
	ResourceName string
	Tags         []string
	TagsSet      bool
}

type migrateOptions struct {
	StatePath string
	OutputDir string
}

func main() {
	opts := parseFlags()
	if err := run(opts); err != nil {
		fmt.Fprintln(os.Stderr, err.Error())
		os.Exit(1)
	}
}

func parseFlags() migrateOptions {
	statePath := flag.String("state", "", "Path to terraform state JSON (terraform state pull > state.json)")
	outputDir := flag.String("out", "", "Directory to write main.tf (default: current directory)")

	flag.Parse()
	return migrateOptions{
		StatePath: strings.TrimSpace(*statePath),
		OutputDir: strings.TrimSpace(*outputDir),
	}
}

func run(opts migrateOptions) error {
	if opts.StatePath == "" {
		return fmt.Errorf("missing -state")
	}

	groups, err := loadGroupsFromState(opts.StatePath)
	if err != nil {
		return err
	}

	profiles, err := loadProfilesFromState(opts.StatePath)
	if err != nil {
		return err
	}

	reportConfigs, err := loadReportConfigsFromState(opts.StatePath)
	if err != nil {
		return err
	}

	customRules, err := loadCustomRulesFromState(opts.StatePath)
	if err != nil {
		return err
	}

	checkSuppressions, err := loadCheckSuppressionsFromState(opts.StatePath)
	if err != nil {
		return err
	}

	applyProfiles, err := loadApplyProfilesFromState(opts.StatePath)
	if err != nil {
		return err
	}

	communicationSettings, err := loadCommunicationSettingsFromState(opts.StatePath)
	if err != nil {
		return err
	}

	if len(groups) == 0 && len(profiles) == 0 && len(reportConfigs) == 0 && len(customRules) == 0 && len(checkSuppressions) == 0 && len(communicationSettings) == 0 && len(applyProfiles) == 0 {
		return fmt.Errorf("\n\x1b[31mwarning: no conformity_group, conformity_profile, conformity_report_config, conformity_custom_rule, conformity_check_suppression, conformity_communication_setting, or conformity_apply_profile resources found in state\x1b[0m")
	}

	var hclLines []string
	hclLines = append(hclLines, boilerplateHCL()...)
	hclLines = append(hclLines, "# Generated by migrate-conformity")

	profileNameCounter := map[string]int{}
	reportConfigNameCounter := map[string]int{}
	customRuleNameCounter := map[string]int{}
	checkSuppressionNameCounter := map[string]int{}
	communicationNameCounter := map[string]int{}
	mappingLines := []string{}
	importLines := []string{"# Import existing Vision One resources"}

	outputDir := opts.OutputDir
	if outputDir == "" {
		var err error
		outputDir, err = os.Getwd()
		if err != nil {
			return fmt.Errorf("get current directory: %w", err)
		}
	}

	dryRun := true
	hclLines, importLines, mappingLines = appendGroupsHCL(hclLines, importLines, mappingLines, groups, dryRun)

	if len(profiles) > 0 {
		hclLines = append(hclLines, "# Profiles")
		for _, item := range profiles {
			resourceName := item.ResourceName
			if resourceName == "" {
				resourceName = toTerraformName(item.Name, profileNameCounter, "profile")
			} else {
				resourceName = uniqueResourceName(resourceName, profileNameCounter)
			}

			hclLines = append(hclLines, fmt.Sprintf("resource \"visionone_crm_profile\" \"%s\" {", resourceName))
			hclLines = append(hclLines, fmt.Sprintf("  name = \"%s\"", escapeHCL(item.Name)))
			if item.Description != "" {
				hclLines = append(hclLines, fmt.Sprintf("  description = \"%s\"", escapeHCL(item.Description)))
			}
			for _, rule := range item.ScanRules {
				hclLines = appendScanRuleHCL(hclLines, rule)
			}
			hclLines = append(hclLines, "}")
			hclLines = append(hclLines, "")

			mappingLines = appendProfileMappingLines(mappingLines, item, resourceName)

			importLines = append(importLines, formatImportLine("visionone_crm_profile", resourceName, item.ID, dryRun))
		}
	}

	if len(reportConfigs) > 0 {
		hclLines = append(hclLines, "# Report Configs")
		for _, item := range reportConfigs {
			resourceName := item.ResourceName
			if resourceName == "" {
				resourceName = toTerraformName(item.ReportTitle, reportConfigNameCounter, "report_config")
			} else {
				resourceName = uniqueResourceName(resourceName, reportConfigNameCounter)
			}
			hclLines = appendReportConfigHCL(hclLines, item, resourceName)
			mappingLines = appendReportConfigMappingLines(mappingLines, item, resourceName)

			importLines = append(importLines, formatImportLine("visionone_crm_report_config", resourceName, item.ID, dryRun))
		}
	}

	if len(customRules) > 0 {
		hclLines = append(hclLines, "# Custom Rules")
		for _, item := range customRules {
			resourceName := item.ResourceName
			if resourceName == "" {
				resourceName = toTerraformName(item.Name, customRuleNameCounter, "custom_rule")
			} else {
				resourceName = uniqueResourceName(resourceName, customRuleNameCounter)
			}
			hclLines = appendCustomRuleHCL(hclLines, item, resourceName)
			mappingLines = appendCustomRuleMappingLines(mappingLines, item, resourceName)

			importLines = append(importLines, formatImportLine("visionone_crm_custom_rule", resourceName, item.ID, dryRun))
		}
	}

	if len(checkSuppressions) > 0 {
		hclLines = append(hclLines, "# Check Suppressions")
		for _, item := range checkSuppressions {
			resourceName := item.ResourceName
			if resourceName == "" {
				resourceName = toTerraformName(item.RuleID, checkSuppressionNameCounter, "check_suppression")
			} else {
				resourceName = uniqueResourceName(resourceName, checkSuppressionNameCounter)
			}
			hclLines = appendCheckSuppressionHCL(hclLines, item, resourceName)
			mappingLines = appendCheckSuppressionMappingLines(mappingLines, item, resourceName)

			importLines = append(importLines, formatImportLine("visionone_crm_check_suppression", resourceName, item.ID, dryRun))
		}
	}

	if len(applyProfiles) > 0 {
		hclLines = append(hclLines, "# Apply Profiles")
		applyProfileNameCounter := map[string]int{}
		for _, item := range applyProfiles {
			resourceName := item.ResourceName
			if resourceName == "" {
				resourceName = toTerraformName(item.ProfileID, applyProfileNameCounter, "apply_profile")
			} else {
				resourceName = uniqueResourceName(resourceName, applyProfileNameCounter)
			}
			hclLines = appendApplyProfileHCL(hclLines, item, resourceName)
			mappingLines = appendApplyProfileMappingLines(mappingLines, item, resourceName)
		}
	}

	if len(communicationSettings) > 0 {
		hclLines = append(hclLines, "# Communication Configurations")
		for _, item := range communicationSettings {
			resourceName := item.ResourceName
			if resourceName == "" {
				resourceName = toTerraformName(item.Name, communicationNameCounter, "communication")
			} else {
				resourceName = uniqueResourceName(resourceName, communicationNameCounter)
			}
			hclLines = appendCommunicationConfigurationHCL(hclLines, item, resourceName)
			mappingLines = appendCommunicationMappingLines(mappingLines, item, resourceName)

			importLines = append(importLines, formatImportLine("visionone_crm_communication_configuration", resourceName, item.ID, dryRun))
		}
	}

	if len(mappingLines) > 0 {
		insertAt := 2
		withMapping := make([]string, 0, len(hclLines)+len(mappingLines)+len(importLines)+10)
		withMapping = append(withMapping, hclLines[:insertAt]...)
		withMapping = append(withMapping, "/*")
		withMapping = append(withMapping, "What was mapped:")
		withMapping = append(withMapping, mappingLines...)
		withMapping = append(withMapping, "*/")
		withMapping = append(withMapping, "")
		withMapping = append(withMapping, "/*")
		withMapping = append(withMapping, "Import commands:")
		withMapping = append(withMapping, importLines...)
		withMapping = append(withMapping, "*/")
		withMapping = append(withMapping, "")
		withMapping = append(withMapping, hclLines[insertAt:]...)
		hclLines = withMapping
	} else if len(importLines) > 0 {
		insertAt := 2
		withImports := make([]string, 0, len(hclLines)+len(importLines)+6)
		withImports = append(withImports, hclLines[:insertAt]...)
		withImports = append(withImports, "/*")
		withImports = append(withImports, "Import commands:")
		withImports = append(withImports, importLines...)
		withImports = append(withImports, "*/")
		withImports = append(withImports, "")
		withImports = append(withImports, hclLines[insertAt:]...)
		hclLines = withImports
	}

	path, err := writeMainTF(outputDir, hclLines)
	if err != nil {
		return err
	}

	fmt.Printf("migrate-conformity: wrote %s\n", path)

	return nil
}

func boilerplateHCL() []string {
	return []string{
		"# Disclaimer: This tool is provided as a helper to migrate terraform resources with no guarantees of accuracy.",
		"# Review the generated configuration with your environment to ensure it does not break anything before applying changes.",
		"",
		"terraform {",
		"  required_providers {",
		"    visionone = {",
		"      source  = \"trendmicro/vision-one\"",
		"      version = \"~> 1.0\"",
		"    }",
		"  }",
		"}",
		"",
		"provider \"visionone\" {",
		"  api_key       = var.api_key",
		"  regional_fqdn = var.regional_fqdn",
		"}",
		"",
		"variable \"api_key\" {",
		"  type    = string",
		"  default = \"\"",
		"}",
		"",
		"variable \"regional_fqdn\" {",
		"  type    = string",
		"  default = \"\"",
		"}",
		"",
	}
}

func loadGroupsFromState(path string) ([]groupItem, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read state: %w", err)
	}

	var state terraformState
	if err := json.Unmarshal(data, &state); err != nil {
		return nil, fmt.Errorf("parse state: %w", err)
	}

	var groups []groupItem
	for _, res := range state.Resources {
		if res.Mode != "managed" || res.Type != "conformity_group" {
			continue
		}
		for _, inst := range res.Instances {
			attrs := inst.Attributes
			if attrs == nil {
				continue
			}
			name, _ := attrs["name"].(string)
			if name == "" {
				continue
			}
			tagsValue, tagsOk := attrs["tags"]
			groups = append(groups, groupItem{
				ID:           toStringValue(attrs["id"]),
				Name:         name,
				ResourceName: resourceNameFromState(res, inst, "group"),
				Tags:         toStringSlice(tagsValue),
				TagsSet:      tagsOk,
			})
		}
	}

	sort.Slice(groups, func(i, j int) bool {
		return groups[i].ResourceName < groups[j].ResourceName
	})

	return groups, nil
}

func writeOutput(path string, lines []string) error {
	content := strings.Join(lines, "\n") + "\n"
	if path == "" {
		fmt.Print(content)
		return nil
	}

	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return fmt.Errorf("write output: %w", err)
	}
	return nil
}
